Repository forbole/big-dipper, pull requests merged in 2019-09, with the labels that each got.

#187 V0.37 fix
  imports/api/accounts/server/methods.js
  imports/api/blocks/server/methods.js
  imports/api/chain/server/methods.js
  imports/api/delegations/server/methods.js
  imports/api/proposals/server/methods.js
  imports/api/validators/server/methods.js
  imports/ui/validators/Validator.jsx
Labels: bug

#190 BigDipper for LikeChain
  both/document.html
  client/styles.css
  imports/ui/accounts/Account.jsx
  imports/ui/blocks/Block.jsx
  imports/ui/blocks/BlocksTable.jsx
  imports/ui/home/Chart.jsx
  imports/ui/home/Home.jsx
  imports/ui/proposals/Proposals.jsx
  imports/ui/stylesheets/bootstrap.min.css
  imports/ui/transactions/Transaction.jsx
  imports/ui/transactions/TransactionsList.jsx
  imports/ui/validators/Validator.jsx
  imports/ui/validators/ValidatorsList.jsx
  imports/ui/voting-power/Distribution.jsx
  imports/ui/voting-power/ThirtyFour.jsx
  imports/ui/voting-power/TwentyEighty.jsx
  imports/ui/voting-power/VotingPower.jsx
  public/img/big-dipper.png
  public/img/big-dipper.svg
Labels: good first issue, likechain

#193 fix account name margin #153
  imports/ui/accounts/Account.jsx
Labels: ux
