Repository forbole/big-dipper, pull requests merged in 2020-01, with the labels that each got.

#245 Spanish version of BigDipper
  both/i18n/en-us.i18n.yml
  both/i18n/es-es.i18n.yml
Labels: good first issue, i18n

#251 Added ChainInfo Component
  imports/ui/components/ChainInfo.jsx
  imports/ui/home/Home.jsx
Labels: R4R

#250 minor fixes to allow opt-out of some features
  imports/api/chain/server/methods.js
  imports/ui/home/Chart.jsx
  package-lock.json
  server/main.js
Labels: good first issue
